### ISSUE TITLE
NoSuchMethodError on travis

### ISSUE THREAD

**Issue by vitor-gyant** [fluttercommunity/flutter_launcher_icons#123]
Hi,

I'm facing a strange issue where the command runs locally but fails on Travis with:

```
[14:02:25]: ---------------------------------------------------------
3145[14:02:25]: --- Step: flutter pub run flutter_launcher_icons:main ---
3146[14:02:25]: ---------------------------------------------------------
3147[14:02:25]: $ flutter pub run flutter_launcher_icons:main
3148[14:02:50]: ▸ Android minSdkVersion = 21
3149[14:02:50]: ▸ Creating default icons Android
3150[14:02:50]: ▸ Overwriting the default Android launcher icon with a new icon
3151[14:02:50]: ▸ Unhandled exception:
3152[14:02:50]: ▸ NoSuchMethodError: The getter 'width' was called on null.
3153[14:02:50]: ▸ Receiver: null
3154[14:02:50]: ▸ Tried calling: width
3155[14:02:50]: ▸ #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
3156[14:02:50]: ▸ #1      overwriteExistingIcons (package:flutter_launcher_icons/android.dart:216:13)
3157[14:02:50]: ▸ #2      createDefaultIcons (package:flutter_launcher_icons/android.dart:45:7)
3158[14:02:50]: ▸ #3      createIconsFromConfig (package:flutter_launcher_icons/main.dart:55:5)
3159[14:02:50]: ▸ <asynchronous suspension>
3160[14:02:50]: ▸ #4      createIconsFromArguments (package:flutter_launcher_icons/main.dart:33:5)
3161[14:02:50]: ▸ <asynchronous suspension>
3162[14:02:50]: ▸ #5      main (file:///Users/travis/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.3/bin/main.dart:4:3)
3163[14:02:50]: ▸ #6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
3164[14:02:50]: ▸ #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
3165[14:02:50]: ▸ pub finished with exit code 255
```

It seems that decodeImage returned a null object but there is not much information to understand why.

Imagemagick is installed together with all the flutter deps . Any idea ?

Thanks,

**Comment by RatakondalaArun** [comment]
Closing this as inactive in case this issue still exists please open a new issue
