### ISSUE TITLE
[BUG] Unhandled exception

### ISSUE THREAD

**Issue by dam322** [fluttercommunity/flutter_launcher_icons#366]
### :information_source: Info
Version: 0.9.2
### :speech_balloon: Description

Enter a description of your problem here
Unhandled exception:

✗ ERROR: InvalidConfigException
Cannot not find minSdk from android/app/build.gradle or android/local.propertiesSpecify minSdk in either android/app/build.gradle or android/local.properties
#0      createIconsFromConfig (package:flutter_launcher_icons/main.dart:96:7)
#1      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)
#2      main (file:///E:/Flutter%20SDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.3/bin/main.dart:7:26)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255

### :scroll: Pubspec.yaml
dev_dependences:
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/pata.png"

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by misako0927** [comment]
I had same problem and I added `flutter.minSdkVersion` to `android/local.properties`.

```
flutter.versionName=1.0.0
flutter.versionCode=1
flutter.minSdkVersion=30 // I added here
```

After added, it works fine.

**Comment by TarasBounty** [comment]
> I had same problem and I added `flutter.minSdkVersion` to `android/local.properties`.
> 
> ```
> flutter.versionName=1.0.0
> flutter.versionCode=1
> flutter.minSdkVersion=30 // I added here
> ```
> 
> After added, it works fine.

works for me too. thanks!

**Comment by ALI-SAMPSON** [comment]
> I had same problem and I added `flutter.minSdkVersion` to `android/local.properties`.
> 
> ```
> flutter.versionName=1.0.0
> flutter.versionCode=1
> flutter.minSdkVersion=30 // I added here
> ```
> 
> After added, it works fine.

Worked for me also, thanks so much!

**Comment by ShaleenThilanka** [comment]
Worked for me also, thanks so much!

**Comment by ShaleenThilanka** [comment]
> I had same problem and I added `flutter.minSdkVersion` to `android/local.properties`.
> 
> ```
> flutter.versionName=1.0.0
> flutter.versionCode=1
> flutter.minSdkVersion=30 // I added here
> ```
> 
> After added, it works fine.

Worked for me also, thanks so much!

**Comment by Dhanabhon** [comment]
> I had same problem and I added `flutter.minSdkVersion` to `android/local.properties`.
> 
> ```
> flutter.versionName=1.0.0
> flutter.versionCode=1
> flutter.minSdkVersion=30 // I added here
> ```
> 
> After added, it works fine.

Thanks, it works.

**Comment by xemexpress** [comment]
> I had same problem and I added `flutter.minSdkVersion` to `android/local.properties`.
> 
> ```
> flutter.versionName=1.0.0
> flutter.versionCode=1
> flutter.minSdkVersion=30 // I added here
> ```
> 
> After added, it works fine.

Thank you!

**Comment by geminixz** [comment]
> 

Thank you!! it work!

**Comment by geminixz** [comment]
> I had same problem and I added `flutter.minSdkVersion` to `android/local.properties`.
> 
> ```
> flutter.versionName=1.0.0
> flutter.versionCode=1
> flutter.minSdkVersion=30 // I added here
> ```
> 
> After added, it works fine.

Thank you!! it work!

**Comment by kapetex** [comment]
thankss!!!
Funcionou certinho!!
