### ISSUE TITLE
Error type String is not a subtype of type 'Map<dynamic, dynamic>'

### ISSUE THREAD

**Issue by esthrim** [fluttercommunity/flutter_launcher_icons#49]
When i run this command 

`$ flutter pub get
$ flutter pub pub run flutter_launcher_icons:main`

it shows error like this 
`Macs-Mac-mini:ultra_approval macmini1$ flutter pub pub run flutter_launcher_icons:main
Unhandled exception:
type 'String' is not a subtype of type 'Map<dynamic, dynamic>'
#0 loadFlutterIconsConfig (package:flutter_launcher_icons/main.dart:42:3)
#1 createIcons.<anonymous closure> (package:flutter_launcher_icons/main.dart:9:18)
#2 _RootZone.runUnary (dart:async/zone.dart:1379:54)
#3 _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5 Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6 Future._complete (dart:async/future_impl.dart:476:7)`

flutter doctor 
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.27.2)
[✓] Connected devices (1 available)
`

**Comment by esthrim** [comment]
Sorry, its my fault i have typo in my pubspec.yaml it solved.
