### ISSUE TITLE
[BUG]  Execution fails when renaming the default Runner project

### ISSUE THREAD

**Issue by ManuelRauber** [fluttercommunity/flutter_launcher_icons#543]
### :information_source: Info

Version: `e.g. v0.13.1`

### :speech_balloon: Description

Flutters [allows to rename the Runner.xcodeproj folder](https://github.com/flutter/flutter/pull/124533). If you do so, the execution of `flutter_launcher_icons` fails:

```
Unhandled exception:
PathNotFoundException: Cannot open file, path = 'ios/Runner.xcodeproj/project.pbxproj' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
<asynchronous suspension>
#2      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562:24)
<asynchronous suspension>
#3      _File.readAsString (dart:io/file_impl.dart:621:18)
<asynchronous suspension>
#4      LineSplitter.convert (dart:convert/line_splitter.dart:52:3)
<asynchronous suspension>
#5      changeIosLauncherIcon (package:flutter_launcher_icons/ios.dart:149:30)
<asynchronous suspension>
```

It would be nice, if this package does support renaming the Runner project as well.

**Comment by bielcarpi** [comment]
As a temporary workaround, we can:

```
cd ios
ln -s Your-Project.xcodeproj Runner.xcodeproj
```

And then run the script. Finally, delete the symlink.
