### ISSUE TITLE
[BUG] ✗ ERROR: NoConfigFoundException No configuration found in flutter_launcher_icons.yaml or in pubspec.yaml. In case file exists in different directory use --file option #0      createIconsFromArguments (package:flutter_launcher_icons/main.dart:75:7) #1      main (file:///C:/Users/ahmed/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_launcher_icons-0.10.0/bin/main.dart:7:26) #2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:294:33) #3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

### ISSUE THREAD

**Issue by AquaSaver** [fluttercommunity/flutter_launcher_icons#545]
### :information_source: Info

Version: `e.g. v0.7.5`

### :speech_balloon: Description

Enter a description of your problem here

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by MarkOSullivan94** [comment]
I cannot help you without you at least least showing your `pubspec.yaml` file
