### ISSUE TITLE
Error when pubspec.yaml contain chinese

### ISSUE THREAD

**Issue by fengqiangboy** [fluttercommunity/flutter_launcher_icons#75]
When my pubspec.yaml description has chinese, it will throw exception;

But I delete chinese, it will fix.

```
name: bbq
description: flutter项目
```

```
Unhandled exception:
Error on line 2, column 25: Unexpected character.
description: flutteré¡¹ç®
                        ^
#0      Parser.parse (package:yaml/src/parser.dart:50:7)
#1      Loader._loadMapping (package:yaml/src/loader.dart:171:23)
#2      Loader._loadNode (package:yaml/src/loader.dart:86:16)
#3      Loader._loadDocument (package:yaml/src/loader.dart:62:20)
#4      Loader.load (package:yaml/src/loader.dart:54:20)
#5      loadYamlDocument (package:yaml/yaml.dart:51:25)
#6      loadYamlNode (package:yaml/yaml.dart:42:5)
#7      loadYaml (package:yaml/yaml.dart:34:5)
#8      YamlConfigParser.parse (package:dart_config/parsers/config_parser_yaml.dart:12:15)
#9      Config.readConfig.<anonymous closure> (package:dart_config/config.dart:44:25)
#10     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
pub finished with exit code 255
```

**Comment by MarkOSullivan94** [comment]
I don't think this is an issue for just this package, I think it's potentially an issue which you should report to the Flutter project: https://github.com/flutter/flutter

**Comment by fengqiangboy** [comment]
But my project is run fine. The exception is throw when I run command `flutter packages pub run flutter_launcher_icons:main`;

**Comment by MarkOSullivan94** [comment]
Your project may run fine but the pubspec.yaml isn't unique to Flutter Launcher Icons, it's a common configuration file used by Flutter projects and other Flutter packages so this issue is out of my control and so cannot help you with this issue.

I hope someone from the Flutter project can help you with this issue.

**Comment by MarkOSullivan94** [comment]
Noticed you posted this already in the Flutter project: https://github.com/flutter/flutter/issues/26340
